version: '3.8'

services:
  api:
    build:
      context: ./ProgressTrackingSystem.Api
      dockerfile: ../Dockerfile
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver-express
    networks:
      - e-learning-networks

  sqlserver-express:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-express
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Rot@2112002"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - e-learning-networks
networks:
  e-learning-networks:
    external: true
volumes:
  db_data:
