services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver-express-pst
    networks:
      - e-learning-network

  sqlserver-express-pst:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-express-pst
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Rot@2112002"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
    networks:
      - e-learning-network
networks:
  e-learning-network:
    external: true
volumes:
  db_data: